POST http://localhost:8085/payment/addPayment
Accept: application/json
Content-Type: application/json

{
  "userId": 6874845
}

###

POST http://localhost:8085/payment/addPaymentCard
Accept: application/json
Content-Type: application/json

{
  "userId": 6874845
}

###
GET http://localhost:8085/payment/allPayments
Accept: application/json

###
GET http://localhost:8089/payment/paymentByUserId?userId=6874845
Accept: application/json

###
GET http://localhost:8089/payment/paymentByUserIdDetails?userId=6874845
Accept: application/json
###
GET http://localhost:8089/payment/paymentReport
Accept: application/json
###

PUT http://localhost:8085/payment/updatePayment
Accept: application/json
Content-Type: application/json

{
  "paymentId": 1,
  "status": 0
}