POST http://localhost:8085/payment/addPayment
Accept: application/json
Content-Type: application/json

{
  "userId": 6874845
}
###
GET http://localhost:8085/payment/allPayments
Accept: application/json