POST http://localhost:8085/plan/addPlan
Accept: application/json
Content-Type: application/json

{
  "userId": 6874845
}
###
GET http://localhost:8085/plan/allPlans
Accept: application/json

###
GET http://localhost:8089/plan/activitiesByPlan?planId=2
Accept: application/json

