POST http://localhost:8085/user/addUser
Accept: application/json
Content-Type: application/json

{
  "idUser": "6874657",
  "userName": "Pedro",
  "lastName": "Salazar",
  "email": "pedro3",
  "password": "pedro@gmail.com",
  "userTypeId": 2,
  "registrantId": 1,
  "planId": null

}
###
GET http://192.168.31.150:8085/user/allUsers
Accept: application/json

###

GET http://192.168.31.150:8085/user/login?email=vega@gmail.com&password=vega
Accept: application/json

###
GET http://192.168.31.150:8085/user/userType?userId=3
Accept: application/json

###
GET http://192.168.31.150:8085/user/userById?userId=5
Accept: application/json

###