POST http://localhost:8080/user/addUser
Accept: application/json
Content-Type: application/json

{
  "userName": "Molly",
  "lastName": "Vargas",
  "email": "vargas123",
  "password": "vargas@gmail.com"
}
###
GET http://localhost:8085/user/allUsers
Accept: application/json