POST http://localhost:8085/userType/addUserType
Accept: application/json
Content-Type: application/json

{
  "type": "Encargado"
}
###
GET http://localhost:8085/userType/allUserTypes
Accept: application/json