POST http://localhost:8085/user/addUser
Accept: application/json
Content-Type: application/json

{
  "userName": "Molly",
  "lastName": "Vargas",
  "email": "vargas123",
  "password": "vargas@gmail.com",
  "userTypeId": 3,
  "registrantId": 1,
  "planId": 1

}
###
GET http://localhost:8085/user/allUsers
Accept: application/json